### ISSUE TITLE
how to use my own fme server?

### ISSUE THREAD

**Issue by liangdwuoi** [safesoftware/fmepedia-easytranslator#1]
I install the fme server 2018 in my pc, which configuration file is setting the server ip and token?

**Comment by lauracwu** [comment]
Hi @xierunhua the server host and token are set in the easyTranslator.js file. These lines are where that existing demo gets them:  
$.getJSON("http://demos.fmeserver.com.s3.amazonaws.com/server-demo-config.json", function(config) {
    BuildForm.host = config.initObject.server;
    BuildForm.token = config.initObject.token;
    FMEServer.init(config.initObject);

For this, they are coming from a json file stored in one of our s3 buckets, to modify this to work with your own server, you can replace those lines with something like this instead:

BuildForm.host = "http://fmeserverurl";     //change this to your FME Server host name or IP
BuildForm.token = "1adfsdaf213j";     //change this to your FME Server token
FMEServer.init({
	server : BuildForm.host,
	token : BuildForm.token
});

We'll add some comments with instructions into the code to make this easier to figure out. Thanks for your feedback on this!

**Comment by esakae** [comment]
Hi,

 $.getJSON("http://demos.fmeserver.com.s3.amazonaws.com/server-demo-config.json", function(config) {
    BuildForm.host = ""http://172.26.23.3:8082"";
    BuildForm.token = "3122f5b252f738893ef93b1b10a48ada8b343df1";
    FMEServer.init({
    server : BuildForm.host,
    token : BuildForm.token
    });

I have update , but it did not change. is there any requirment

**Comment by steveatsafe** [comment]
Hi @emincaglauluc ,
When you say - it did not change, are you saying the same .json file values are persisting?  

If so, I think you may need to change the code a bit more... in lauracwu's comment she removes that getJSON all together - just make sure that the json file isn't factoring into this call at all.

BuildForm.host = ""http://172.26.23.3:8082"";
BuildForm.token = "3122f5b252f738893ef93b1b10a48ada8b343df1";
FMEServer.init({
server : BuildForm.host,
token : BuildForm.token
});

**Comment by esakae** [comment]
Yes, I hoped that when I change the host and token that my own server (workbench) will work.
I would like make some changes in the eastTranslate workbench.
So, you are saying I need to change the code. I got it. I am the new in this world : )
Thank you @steveatsafe
