### ISSUE TITLE
FME Workspace is broken?

### ISSUE THREAD

**Issue by runneals** [safesoftware/fmepedia-easytranslator#3]
When I try to upload a csv, the csv that I get back is completely empty or one that just has ,,,, ,,,, ,,,, ,,,,

**Comment by lauracwu** [comment]
Thanks @runneals! We'll check it out and get a fix in as soon as we can.

**Comment by lauracwu** [comment]
Updated the workspace using the same workaround mentioned in: https://community.safe.com/s/question/0D54Q00009BsNfSSAV/working-with-fields-and-published-parameters-in-dynamic-workspaces
